version: '3.8'

services:
  app:
    build: .
    image: uvproduction
    container_name: bybit-data-collector
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped